# This rule is not used by the project pv-reclaimer-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over reclaim.pv-reclaimer.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pv-reclaimer-controller
    app.kubernetes.io/managed-by: kustomize
  name: pvreclaim-admin-role
rules:
- apiGroups:
  - reclaim.pv-reclaimer.io
  resources:
  - pvreclaims
  verbs:
  - '*'
- apiGroups:
  - reclaim.pv-reclaimer.io
  resources:
  - pvreclaims/status
  verbs:
  - get
