---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - reclaim.pv-reclaimer.io
  resources:
  - pvreclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - reclaim.pv-reclaimer.io
  resources:
  - pvreclaims/finalizers
  verbs:
  - update
- apiGroups:
  - reclaim.pv-reclaimer.io
  resources:
  - pvreclaims/status
  verbs:
  - get
  - patch
  - update
