apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.controller.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: pv-reclaimer-controller
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: pv-reclaimer-controller
  replicas: {{ .Values.controller.replicas }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: pv-reclaimer-controller
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        # overrides the ENTRYPOINT in docker image
      - command:
        - /manager
        # overrides the CMD in docker image
        args:
          - --leader-elect
          - --health-probe-bind-address=:8081
        image: {{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}
        name: pv-reclaim
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        # Checks whether the pod is alive and running or not
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        # Checks whether the pod is ready to receive the application traffic or not
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: {{ .Values.serviceAccount.name }}
      terminationGracePeriodSeconds: 10
