---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.role.name }}
rules:
- apiGroups:
  - reclaim.pv-reclaimer.io
  resources:
  - pvreclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - reclaim.pv-reclaimer.io
  resources:
  - pvreclaims/finalizers
  verbs:
  - update
- apiGroups:
  - reclaim.pv-reclaimer.io
  resources:
  - pvreclaims/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups: [""] # core API group
  resources: ["persistentvolumes"]
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups: [""] # Core API group
  resources: ["events"]
  verbs:
  - create
  - patch